### Get all users
GET http://localhost:3000/users
Content-Type: application/json

###

### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Caio",
    "email": "caiomirandab@gmail.com"
}
